### ISSUE TITLE
RAE API updated potentially

### ISSUE THREAD

**Issue by librehat** [Tsur/node-rae#11]
## Issue Type

- [x] Bug
- [ ] Feature

## Description

```
> cli.search("diccionario").then(resp => console.log(resp)).catch(e => console.log(e));
Promise { <pending> }
> Error: "No challenge SCRIPT found!, It is possible due to RAE updated its API. Please raise an issue at https://github.com/Tsur/node-rae/issues" parser error found. Please raise an issue at https://github.com/Tsur/node-rae/issues
    at o.ParserError (/home/symeon/node_modules/rae/build/lib.js:1:12242)
    at /home/symeon/node_modules/rae/build/lib.js:1:13774
    at new Promise (<anonymous>)
    at o.parseAuthData (/home/symeon/node_modules/rae/build/lib.js:1:13312)
    at o.default (/home/symeon/node_modules/rae/build/lib.js:1:14709)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async /home/symeon/node_modules/rae/build/lib.js:1:12923
```

## Steps to reproduce

There is also another bug, the error handling is incorrect, so now if I do 
```
$ rae diccionario
```
This would throw an exception and exit with non zero values.

To reproduce the main issue which is the result of API change, it can be done by querying any words.

# Versions

- Rae (see `package.json`): 1.0.3
- Node/NPM: 12.13.0
- Browser: Firefox (not relevant here)

**Comment by tsur** [comment]
Hi, thanks for reporting it.

feel free to make a PR with a fix, ow I'll take a look asap.

thanks so much
